apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-cd
images:
- name: container-to-change-cd
  newName: quaredevil/ci-gitops-test
  newTag: 7a543daa2ab11a3f567348739a62247af656901f
commonLabels:
  node.finance.99app.com/environment: development
resources:
- ../../base
