apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-cd
images:
- name: container-to-change-cd
  newName: quaredevil/ci-gitops-test
  newTag: b89f286f0a0d5c3adcf83d72cdcbb27447a00112
commonLabels:
  node.finance.99app.com/environment: development
resources:
- ../../base
