apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-cd
images:
- name: container-to-change-cd
  newName: quaredevil/ci-gitops-test
  newTag: 5237c82930516440eafdff3cdf9496900f0dad72
commonLabels:
  node.finance.99app.com/environment: development
resources:
- ../../base
