apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-cd
images:
- name: container-to-change-cd
  newName: quaredevil/ci-gitops-test
  newTag: 713886e631d02802f0eb071663367d40805fec47
commonLabels:
  node.finance.99app.com/environment: development
resources:
- ../../base
