apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-cd
images:
- name: container-to-change-cd
  newName: quaredevil/ci-gitops-test
  newTag: 3118a149210a7696afb76e93d48dd25d688a68f7
commonLabels:
  node.finance.99app.com/environment: development
resources:
- ../../base
