apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-cd
images:
- name: container-to-change-cd
  newName: quaredevil/ci-gitops-test
  newTag: 4c777d19cd108175fa9b764a39bb11e1418b895b
commonLabels:
  node.finance.99app.com/environment: development
resources:
- ../../base
