apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-cd
images:
- name: container-to-change-cd
  newName: quaredevil/ci-gitops-test
  newTag: f3f6d24ef31aa2f1be7106f8db1e6b9bed49140c
commonLabels:
  node.finance.99app.com/environment: development
resources:
- ../../base
