apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-cd
images:
- name: container-to-change-cd
  newName: quaredevil/ci-gitops-test
  newTag: 4e0dd4c77a231f0122ffd155a86fda02b990f2fc
commonLabels:
  node.finance.99app.com/environment: development
resources:
- ../../base
