apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-cd
images:
- name: container-to-change-cd
  newName: quaredevil/ci-gitops-test
  newTag: fbf31493ce7e28295a28e8a0925cde251ae7d2d3
commonLabels:
  node.finance.99app.com/environment: development
resources:
- ../../base
