apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-cd
images:
- name: container-to-change-cd
  newName: quaredevil/ci-gitops-test
  newTag: 65eb4ce626834814a3855fe2691b6088473a32c6
commonLabels:
  node.finance.99app.com/environment: development
resources:
- ../../base
