exclude:
    ^.vscode/
    ^.github/
    ^doc/
    ^newsfragments/
    ^htmlcov/

repos:
#-   repo: local
#    hooks:
#    -   id: system
#        name: Requirements
#        entry: poetry export --format=requirements.txt --without-hashes --dev --output=doc/requirements.txt
#        pass_filenames: false
#        language: system

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
        exclude: '^(install|get)-poetry.py$'

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys]
    -   id: check-ast
    -   id: debug-statements
    -   id: check-docstring-first
    -   id: detect-private-key
    -   id: check-added-large-files
    -   id: check-builtin-literals

-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.2
    hooks:
    -   id: seed-isort-config

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        additional_dependencies: ['toml']

-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
        language_version: python3.8


-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -    id: flake8
         additional_dependencies: ['flake8-docstrings', 'darglint']
