name: ci-deploy

on:
  pull_request:
    branches:
    - main
    - 'release/**'

  push:
    branches:
    - main    
    - 'release/**'

env:
  python-version: 3.8

jobs: 

  build-container:
    name: Build Container
    
    #needs:
    #if: github.event_name == 'push'
    
    runs-on: ubuntu-latest

    steps:

      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2

      #----------------------------------------------
      #Log in to Docker Hub
      #----------------------------------------------
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      #----------------------------------------------
      #Build and push
      #----------------------------------------------
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_IMAGE }}:dev-latest
            ${{ secrets.DOCKERHUB_IMAGE }}:dev-${{ github.sha }}



