name: ci-git-release

on:
  push:
    tags:
      - '*'


jobs: 

  github-release:
    name: Releases

    runs-on: ubuntu-latest

    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: 💾 Repository | Check out
        uses: actions/checkout@v2


      #----------------------------------------------
      # Releases 
      #----------------------------------------------
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true