name: continuous-integration-pull-request

on:
  pull_request:
    branches:
    - main
    - release

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    #----------------------------------------------
    #       check-out repo
    #----------------------------------------------
    - name: Check out repository
      uses: actions/checkout@v2
    #----------------------------------------------
    #Run coverage tests
    #----------------------------------------------
    - name: pytest-coverage-commentator
      uses: coroo/pytest-coverage-commentator@v1.0.2
      with:
        pytest-coverage: pytest-coverage.txt