name: continuous_integration

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code, library action
    - uses: actions/checkout@v2

    # Set-up python
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v2.1.7
      with:
        path: |
          ~/.cache/pypoetry
          .venv
        key: poetry-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
    
    #Install poetry
    - name: Install poetry no matter what
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    #Install requirements
    - name: Install requirements
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: |
        poetry install

    # Run Linting
    - name: Run pre-commit hooks (Linting)
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pre-commit install
        pre-commit run --all-files

    # Run python tests
    - name: Test with pytest
      run: |
        poetry install
        poetry run pytest
